-- Author Pro: a paid plan for writers.
--
-- Written by hand rather than generated by `prisma migrate dev`, because this
-- database has pre-existing drift against its migration history and
-- `migrate dev` insists on a full reset (dropping all data) before it will
-- generate anything. Every statement here is additive — a new table and two new
-- nullable/defaulted columns — so it applies safely to a populated database.
--
-- Table names are lowercase and constraint names PascalCase to match the
-- conventions already established in the baseline migration.

-- CreateTable
CREATE TABLE `authorsubscription` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `stripeCustomerId` VARCHAR(191) NOT NULL,
    `stripeSubscriptionId` VARCHAR(191) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'inactive',
    `plan` VARCHAR(191) NOT NULL DEFAULT 'monthly',
    `currentPeriodEnd` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `userId` INTEGER NOT NULL,

    UNIQUE INDEX `AuthorSubscription_stripeSubscriptionId_key`(`stripeSubscriptionId` ASC),
    UNIQUE INDEX `AuthorSubscription_userId_key`(`userId` ASC),
    INDEX `AuthorSubscription_stripeCustomerId_idx`(`stripeCustomerId` ASC),
    INDEX `AuthorSubscription_status_idx`(`status` ASC),
    PRIMARY KEY (`id` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `authorsubscription` ADD CONSTRAINT `AuthorSubscription_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AlterTable: grandfather flag for authors who predate the paywall
ALTER TABLE `user` ADD COLUMN `authorGrandfathered` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable: bundles can now belong to an author (NULL = existing admin/site bundle)
ALTER TABLE `storybundle` ADD COLUMN `authorId` INTEGER NULL;

-- CreateIndex
CREATE INDEX `StoryBundle_authorId_idx` ON `storybundle`(`authorId` ASC);

-- AddForeignKey
ALTER TABLE `storybundle` ADD CONSTRAINT `StoryBundle_authorId_fkey` FOREIGN KEY (`authorId`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
